# This YAML file describes your package. Stack will automatically
# generate a Cabal file when you run `stack build`. See the hpack
# website for help with this file: <https://github.com/sol/hpack>.
benchmarks:
  wavetoy2-benchmarks:
    dependencies:
    - base
    - wavetoy2
    - criterion
    ghc-options:
    - -O2
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Other
description: wavetoy2 is a Haskell WaveToy implementation
executables:
  wavetoy2:
    dependencies:
    - base
    - monad-loops
    - vector-space
    - wavetoy2
    ghc-options:
    - -O2
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.rst
- LICENSE.rst
- package.yaml
- README.rst
- stack.yaml
ghc-options: -Wall
github: eschnett/wavetoy2
library:
  dependencies:
  - base
  - comonad
  - vector
  - vector-space
  source-dirs: library
license: MIT
maintainer: Erik Schnetter
name: wavetoy2
synopsis: wavetoy2 is a Haskell WaveToy implementation
tests:
  wavetoy2-test-suite:
    dependencies:
    - base
    - ieee754
    - tasty
    - tasty-hspec
    - tasty-quickcheck
    - tasty-smallcheck
    - vector
    - wavetoy2
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '1.0.0'
